server:
  port: 9097

spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: service1
          uri: http://localhost:8183/documents/get-doc-by-text
          predicates:
            - Path=/documents/get-doc-by-text
          filters:
            - RewritePath=/documents/get-doc-by-text(?<path>.*), /$\{path}