/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package cl.sugarfever.kafka.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Imagen extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4369961876325616406L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Imagen\",\"namespace\":\"cl.sugarfever.kafka.avro\",\"fields\":[{\"name\":\"idimagen\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\",\"logicalType\":\"UUID\"}},{\"name\":\"url\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Imagen> ENCODER =
      new BinaryMessageEncoder<Imagen>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Imagen> DECODER =
      new BinaryMessageDecoder<Imagen>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Imagen> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Imagen> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Imagen> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Imagen>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Imagen to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Imagen from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Imagen instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Imagen fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String idimagen;
   private java.lang.String url;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Imagen() {}

  /**
   * All-args constructor.
   * @param idimagen The new value for idimagen
   * @param url The new value for url
   */
  public Imagen(java.lang.String idimagen, java.lang.String url) {
    this.idimagen = idimagen;
    this.url = url;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return idimagen;
    case 1: return url;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: idimagen = value$ != null ? value$.toString() : null; break;
    case 1: url = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'idimagen' field.
   * @return The value of the 'idimagen' field.
   */
  public java.lang.String getIdimagen() {
    return idimagen;
  }


  /**
   * Sets the value of the 'idimagen' field.
   * @param value the value to set.
   */
  public void setIdimagen(java.lang.String value) {
    this.idimagen = value;
  }

  /**
   * Gets the value of the 'url' field.
   * @return The value of the 'url' field.
   */
  public java.lang.String getUrl() {
    return url;
  }


  /**
   * Sets the value of the 'url' field.
   * @param value the value to set.
   */
  public void setUrl(java.lang.String value) {
    this.url = value;
  }

  /**
   * Creates a new Imagen RecordBuilder.
   * @return A new Imagen RecordBuilder
   */
  public static cl.sugarfever.kafka.avro.Imagen.Builder newBuilder() {
    return new cl.sugarfever.kafka.avro.Imagen.Builder();
  }

  /**
   * Creates a new Imagen RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Imagen RecordBuilder
   */
  public static cl.sugarfever.kafka.avro.Imagen.Builder newBuilder(cl.sugarfever.kafka.avro.Imagen.Builder other) {
    if (other == null) {
      return new cl.sugarfever.kafka.avro.Imagen.Builder();
    } else {
      return new cl.sugarfever.kafka.avro.Imagen.Builder(other);
    }
  }

  /**
   * Creates a new Imagen RecordBuilder by copying an existing Imagen instance.
   * @param other The existing instance to copy.
   * @return A new Imagen RecordBuilder
   */
  public static cl.sugarfever.kafka.avro.Imagen.Builder newBuilder(cl.sugarfever.kafka.avro.Imagen other) {
    if (other == null) {
      return new cl.sugarfever.kafka.avro.Imagen.Builder();
    } else {
      return new cl.sugarfever.kafka.avro.Imagen.Builder(other);
    }
  }

  /**
   * RecordBuilder for Imagen instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Imagen>
    implements org.apache.avro.data.RecordBuilder<Imagen> {

    private java.lang.String idimagen;
    private java.lang.String url;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(cl.sugarfever.kafka.avro.Imagen.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.idimagen)) {
        this.idimagen = data().deepCopy(fields()[0].schema(), other.idimagen);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.url)) {
        this.url = data().deepCopy(fields()[1].schema(), other.url);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Imagen instance
     * @param other The existing instance to copy.
     */
    private Builder(cl.sugarfever.kafka.avro.Imagen other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.idimagen)) {
        this.idimagen = data().deepCopy(fields()[0].schema(), other.idimagen);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.url)) {
        this.url = data().deepCopy(fields()[1].schema(), other.url);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'idimagen' field.
      * @return The value.
      */
    public java.lang.String getIdimagen() {
      return idimagen;
    }


    /**
      * Sets the value of the 'idimagen' field.
      * @param value The value of 'idimagen'.
      * @return This builder.
      */
    public cl.sugarfever.kafka.avro.Imagen.Builder setIdimagen(java.lang.String value) {
      validate(fields()[0], value);
      this.idimagen = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'idimagen' field has been set.
      * @return True if the 'idimagen' field has been set, false otherwise.
      */
    public boolean hasIdimagen() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'idimagen' field.
      * @return This builder.
      */
    public cl.sugarfever.kafka.avro.Imagen.Builder clearIdimagen() {
      idimagen = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'url' field.
      * @return The value.
      */
    public java.lang.String getUrl() {
      return url;
    }


    /**
      * Sets the value of the 'url' field.
      * @param value The value of 'url'.
      * @return This builder.
      */
    public cl.sugarfever.kafka.avro.Imagen.Builder setUrl(java.lang.String value) {
      validate(fields()[1], value);
      this.url = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'url' field has been set.
      * @return True if the 'url' field has been set, false otherwise.
      */
    public boolean hasUrl() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'url' field.
      * @return This builder.
      */
    public cl.sugarfever.kafka.avro.Imagen.Builder clearUrl() {
      url = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Imagen build() {
      try {
        Imagen record = new Imagen();
        record.idimagen = fieldSetFlags()[0] ? this.idimagen : (java.lang.String) defaultValue(fields()[0]);
        record.url = fieldSetFlags()[1] ? this.url : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Imagen>
    WRITER$ = (org.apache.avro.io.DatumWriter<Imagen>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Imagen>
    READER$ = (org.apache.avro.io.DatumReader<Imagen>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.idimagen);

    out.writeString(this.url);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.idimagen = in.readString();

      this.url = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.idimagen = in.readString();
          break;

        case 1:
          this.url = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










