server:
  port: 8761

spring:
  application:
    name: eureka-discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    appname: service-registry-cluster
#  server:
#    enable-self-preservation: false
#    expected-client-renewal-interval-seconds: 3
#    eviction-interval-timer-in-ms: 2000

logging:
  level:
    ROOT: DEBUG
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

log:
  app-name: discovery-service