version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:14.4-alpine
    profiles:
      - scrap
      - back
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - "postgres:/var/lib/postgresql/data"
    restart: always
    networks:
      - ${GLOBAL_NETWORK:-kafka}
volumes:
  postgres:
    driver: local